### ISSUE TITLE
Error  during  feeding  data to the  BPR

### ISSUE THREAD

**Issue by AzizIlyosov** [wuga214/NCE_Projected_LRec#36]
I've  runned script  by following  command :
```
(tensorflow) e:\NCE\NCE_Projected_LRec>python main.py -i 4 -l 1.0 -r 100 -a 10 -
m BPR  -d datax/ -t Rtrain.npz -v Rvalid.npz -k 10
```
and  I got  this error:
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main(args)
  File "main.py", line 89, in main
    lam=args.lamb, alpha=args.alpha, seed=args.seed, root=args.root)
  File "e:\NCE\NCE_Projected_LRec\models\bpr.py", line 148, in bpr
    model.train_model(matrix_input, iteration)
  File "e:\NCE\NCE_Projected_LRec\models\bpr.py", line 131, in train_model
    training = self.sess.run([self.optimizer], feed_dict=feed_dict)
  File "C:\Users\Aziz\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\pyt
hon\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\Aziz\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\pyt
hon\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Aziz\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\pyt
hon\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\Aziz\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\pyt
hon\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unsupported feed type

**Comment by AzizIlyosov** [comment]
Thank  for  your  answer .  You are  right  right  now  I am using  python3 . I'll  try  with python2
